version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # Check for updates at 9am UTC each monday
      interval: "weekly"
      time: "09:00"
      day: "monday"
    target-branch: "develop"
    labels:
      - "dependencies"
    reviewers:
      - "ElvisKrop"
      - "yusufseyrek"
