name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12.22.8
          cache: 'yarn'

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1.6
        with:
          install-command: yarn --frozen-lockfile --silent

      - name: Code Generation
        run: yarn codegen

      - name: Build
        run: yarn build
