name: Deploy The Graph on Ethereum Mainnet

on:
  workflow_call:
    secrets:
      THE_GRAPH_ACCESS_TOKEN:
        required: true
    inputs:
      SUBGRAPH_NAME:
        default: trade-mainnet
        type: string
        required: true
        description: Specify a subgraph name

  workflow_dispatch:
    inputs:
      SUBGRAPH_NAME:
        type: choice
        description: Are you going to deploy a stable or beta version?
        required: true
        default: trade-mainnet
        options:
          - trade-mainnet
          - trade-mainnet-beta

jobs:
  deploy-mainnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.8
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          SUBGRAPH_NAME: ${{ inputs.SUBGRAPH_NAME }}${{ github.event.inputs.SUBGRAPH_NAME }}
          GRAPH_CONFIG_FILE: "subgraph.yaml"
        run: yarn deploy
