name: Deploy Graph on Mumbai

on:
  workflow_call:
    secrets:
      THE_GRAPH_ACCESS_TOKEN:
        required: true
    inputs:
      SUBGRAPH_NAME:
        default: trade-mumbai
        type: string
        required: false
        description: Specify a subgraph name

  workflow_dispatch:
    inputs:
      SUBGRAPH_NAME:
        type: choice
        description: Are you going to deploy a stable or beta version?
        required: true
        default: trade-mumbai
        options:
          - trade-mumbai
          - trade-mumbai-beta

jobs:
  deploy-mumbai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12.22.8
          cache: 'yarn'

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1.6
        with:
          install-command: yarn --frozen-lockfile --silent

      - name: Code Generation
        env:
          GRAPH_CONFIG_FILE: "subgraph.mumbai.yaml"
        run: yarn codegen

      - name: Build
        run: yarn build

      - name: Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          SUBGRAPH_NAME: ${{ inputs.SUBGRAPH_NAME }}${{ github.event.inputs.SUBGRAPH_NAME }}
          GRAPH_CONFIG_FILE: "subgraph.mumbai.yaml"
        run: yarn deploy
