name: Deploy Stable Graphs

on:
  push:
    branches: [ main ]

jobs:
  deploy-stable-mainnet:
    uses: swarmmarkets/trade-subgraph/.github/workflows/graph.mainnet.yml@master
    with:
      SUBGRAPH_NAME: trade-mainnet
    secrets:
      GRAPH_ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}

  deploy-stable-rinkeby:
    uses: swarmmarkets/trade-subgraph/.github/workflows/graph.rinkeby.yml@master
    with:
      SUBGRAPH_NAME: trade-rinkeby
    secrets:
      GRAPH_ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}

#  deploy-stable-polygon:
#    uses: swarmmarkets/trade-subgraph/.github/workflows/graph.polygon.yml@master
#    with:
#      SUBGRAPH_NAME: trade-polygon
#    secrets:
#      GRAPH_ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}

  deploy-stable-mumbai:
    uses: swarmmarkets/trade-subgraph/.github/workflows/graph.mumbai.yml@master
    with:
      SUBGRAPH_NAME: trade-mumbai
    secrets:
      GRAPH_ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}
