name: Deploy Beta Graphs

on:
  push:
    branches: [ develop ]

jobs:
  deploy-beta-mainnet:
    uses: SwarmMarkets/trade-subgraph/.github/workflows/graph.mainnet.yml@develop
    with:
      SUBGRAPH_NAME: trade-mainnet-beta
    secrets:
      THE_GRAPH_ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}

  deploy-beta-rinkeby:
    uses: SwarmMarkets/trade-subgraph/.github/workflows/graph.rinkeby.yml@develop
    with:
      SUBGRAPH_NAME: trade-rinkeby-beta
    secrets:
      THE_GRAPH_ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}

  deploy-beta-polygon:
    uses: SwarmMarkets/trade-subgraph/.github/workflows/graph.polygon.yml@develop
    with:
      SUBGRAPH_NAME: trade-polygon-beta
    secrets:
      THE_GRAPH_ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}

  deploy-beta-mumbai:
    uses: SwarmMarkets/trade-subgraph/.github/workflows/graph.mumbai.yml@develop
    with:
      SUBGRAPH_NAME: trade-mumbai-beta
    secrets:
      THE_GRAPH_ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}
