name: Deploy The Graph on Polygon Mainnet

on:
  workflow_call:
    inputs:
      subgraph_name:
        default: "trade-polygon"
        type: string
        required: true
        description: Specify a subgraph name

  workflow_dispatch:
    inputs:
      subgraph_name:
        type: choice
        description: Are you going to deploy a stable or beta version?
        required: true
        default: "trade-polygon"
        options:
          - "trade-polygon"
          - "trade-polygon-beta"

jobs:
  deploy-polygon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.8
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          SUBGRAPH_NAME: ${{ github.event.inputs.subgraph_name }}
          GRAPH_CONFIG_FILE: "subgraph.polygon.yaml"
        run: yarn deploy
