name: Deploy Graph on Ethereum Mainnet

on:
  workflow_call:
    secrets:
      THE_GRAPH_ACCESS_TOKEN:
        required: true
    inputs:
      SUBGRAPH_NAME:
        default: trade-mainnet
        type: string
        required: false
        description: Specify a subgraph name

  workflow_dispatch:
    inputs:
      SUBGRAPH_NAME:
        type: choice
        description: Are you going to deploy a stable or beta version?
        required: true
        default: trade-mainnet
        options:
          - trade-mainnet
          - trade-mainnet-beta

jobs:
  deploy-mainnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get yarn cache
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies if cache is not found
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Generate configuration file
        env:
          NETWORK: mainnet
        run: yarn generate:config

      - name: Code Generation
        run: yarn codegen

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          SUBGRAPH_NAME: ${{ inputs.SUBGRAPH_NAME }}${{ github.event.inputs.SUBGRAPH_NAME }}
        run: yarn deploy
